#--------------- 快捷键 ---------------
unbind C-b
set -g prefix C-M-S-b # 设置 prefix 为 caps lock + b

unbind '|'
bind '|' split-window -h # Create vertical split

unbind '-'
bind - split-window -v # Create horizontal split
#-----------------------------------

set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'
setw -g mode-keys vi

# 启用插件管理器 tpm
set -g @plugin 'tmux-plugins/tpm'

# 启用 sensible 插件，提供一些有用的默认设置
set -g @plugin 'tmux-plugins/tmux-sensible'

#------------ Session 持久化 ------------
# 保存： 按 Prefix + Ctrl-s (Save)。你会看到状态栏显示 "Saved"。
# 恢复： 按 Prefix + Ctrl-r (Restore)。你会看到状态栏显示 "Restored"。
set -g @plugin 'tmux-plugins/tmux-resurrect' # 保存和恢复 session 的基础插件
set -g @plugin 'tmux-plugins/tmux-continuum' # 自动保存并自动启动（依赖 resurrect）

set -g @continuum-restore 'on' # 开启自动恢复 session
set -g @continuum-save-interval '15' # 设置自动保存间隔（单位：分钟）
set -g @resurrect-capture-pane-contents 'on' # (可选) 恢复面板内容（实验性）
#------------ ----------------------------


#---------------- 主题 ------------
set -g @plugin 'omerxx/catppuccin-tmux'

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "directory date_time" # date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"
set -g @catppuccin_date_time_text "%a %y/%m/%d %H:%M"
set -g @catppuccin_status_background "theme"
#-----------------------------------


# ---------------------------- 浮动终端 ----------------------------
# 在 tmux 里提供一个 可开关的「浮动终端」弹层：
# 像一块盖在当前布局上的大窗口，用来临时跑命令，而不改你原来的分屏结构
set -g @plugin 'omerxx/tmux-floax'

set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-bind 'p'  # prifix + p 打开浮动终端, ctril +d 关闭浮动终端
set -g @floax-change-path 'true'
# ------------------------------------------------------------


set -g @plugin 'tmux-plugins/tmux-yank' # 在 tmux 里复制就像 Cmd+C 一样好用


run '~/.tmux/plugins/tpm/tpm'
