#!/bin/bash
# Renderer: borders (window border coloring). With --apply, restarts the daemon.
set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
# shellcheck source=../../lib/color.sh
source "$DOTFILES_DIR/system/lib/color.sh"

OUTPUT="${DOTFILES_DIR}/system/themes/generated/borders-colors.sh"

BORDERS_ACTIVE_COLOR=$(color_hex_to_argb "$THEME_PRIMARY")
BORDERS_INACTIVE_COLOR="${THEME_BORDERS_INACTIVE_COLOR:-0x00000000}"
BORDERS_WIDTH="${THEME_BORDERS_WIDTH:-5.0}"

cat > "$OUTPUT" <<EOF
#!/bin/bash
# Generated by theme system. Do not edit by hand.
export BORDERS_ACTIVE_COLOR="${BORDERS_ACTIVE_COLOR}"
export BORDERS_INACTIVE_COLOR="${BORDERS_INACTIVE_COLOR}"
export BORDERS_WIDTH="${BORDERS_WIDTH}"
EOF

echo "  ✨ borders-colors.sh"

if [[ "${1:-}" == "--apply" ]]; then
  if command -v /opt/homebrew/bin/borders &>/dev/null; then
    /usr/bin/pkill -x borders >/dev/null 2>&1 || true
    nohup /opt/homebrew/bin/borders \
      "active_color=$BORDERS_ACTIVE_COLOR" \
      "inactive_color=$BORDERS_INACTIVE_COLOR" \
      "width=$BORDERS_WIDTH" >/dev/null 2>&1 &
    echo "  🔄 borders restarted"
  fi
fi
