#!/bin/bash
# Renderer:Borders (window border coloring)
# Reads THEME_XX env vars and generates a shell script exporting border colors.
# Pass --apply to also restart the borders process.

set -euo pipefail

OUTPUT="${DOTFILES_DIR}/system/themes/generated/borders-colors.sh"

_blue="${THEME_BLUE#\#}"
_surface1="${THEME_SURFACE1#\#}"

BORDERS_ACTIVE_COLOR="0xff${_blue}"
BORDERS_INACTIVE_COLOR="0xff${_surface1}"

cat > "$OUTPUT" <<EOF
#!/bin/bash
# Generated by theme system. Do not edit by hand.
export BORDERS_ACTIVE_COLOR="${BORDERS_ACTIVE_COLOR}"
export BORDERS_INACTIVE_COLOR="${BORDERS_INACTIVE_COLOR}"
EOF

echo "Generated $OUTPUT"

if [[ "${1:-}" == "--apply" ]]; then
  if command -v /opt/homebrew/bin/borders &>/dev/null; then
    pkill -x borders >/dev/null 2>&1 || true
    nohup /opt/homebrew/bin/borders \
      "active_color=$BORDERS_ACTIVE_COLOR" \
      "inactive_color=$BORDERS_INACTIVE_COLOR" \
      "width=8.0" >/dev/null 2>&1 &
    echo "Borders restarted with new colors."
  fi
fi
