#!/bin/bash
# Renderer: Ghostty.
#   - If THEME_GHOSTTY_BUILTIN is set, point config at that built-in theme.
#   - Otherwise generate a custom theme from THEME_* colors.
set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
CONFIG="${DOTFILES_DIR}/modules/ghostty/config"
THEMES_DIR="${DOTFILES_DIR}/modules/ghostty/themes"

builtin="${THEME_GHOSTTY_BUILTIN:-}"

if [[ -n "$builtin" ]]; then
  sed -i '' "s/^theme = .*/theme = ${builtin}/" "$CONFIG"
  rm -f "$THEMES_DIR/my-theme"
  echo "  ✨ ghostty → ${builtin}"
else
  mkdir -p "$THEMES_DIR"
  sed -i '' "s/^theme = .*/theme = my-theme/" "$CONFIG"
  cat > "$THEMES_DIR/my-theme" <<EOF
# Generated by dotfiles theme system. Do not edit by hand.
background = ${THEME_BG}
foreground = ${THEME_FG}
cursor-color = ${THEME_PRIMARY}

palette = 0=${THEME_BLACK}
palette = 1=${THEME_RED}
palette = 2=${THEME_GREEN}
palette = 3=${THEME_YELLOW}
palette = 4=${THEME_BLUE}
palette = 5=${THEME_MAGENTA}
palette = 6=${THEME_CYAN}
palette = 7=${THEME_WHITE}
palette = 8=${THEME_BLACKB}
palette = 9=${THEME_REDB}
palette = 10=${THEME_GREENB}
palette = 11=${THEME_YELLOWB}
palette = 12=${THEME_BLUEB}
palette = 13=${THEME_MAGENTAB}
palette = 14=${THEME_CYANB}
palette = 15=${THEME_WHITEB}

selection-background = ${THEME_OUTLINE}
selection-foreground = ${THEME_FG}
EOF
  echo "  ✨ ghostty → my-theme (custom)"
fi
