#!/bin/bash
# Renderer: Ghostty custom theme
# Generates a Ghostty theme file from THEME_* variables.

set -euo pipefail

OUTPUT="${DOTFILES_DIR}/modules/ghostty/themes/my-theme"

mkdir -p "${DOTFILES_DIR}/modules/ghostty/themes"

cat > "$OUTPUT" <<EOF
# Generated by dotfiles theme system. Do not edit by hand.
background = ${THEME_BASE}
foreground = ${THEME_TEXT}
cursor-color = ${THEME_CURSOR}

palette = 0=${THEME_CRUST}
palette = 1=${THEME_RED}
palette = 2=${THEME_GREEN}
palette = 3=${THEME_YELLOW}
palette = 4=${THEME_BLUE}
palette = 5=${THEME_MAUVE}
palette = 6=${THEME_TEAL}
palette = 7=${THEME_OVERLAY1}
palette = 8=${THEME_OVERLAY0}
palette = 9=${THEME_MAROON}
palette = 10=${THEME_PEACH}
palette = 11=${THEME_SUBTEXT0}
palette = 12=${THEME_SAPPHIRE}
palette = 13=${THEME_SKY}
palette = 14=${THEME_FLAMINGO}
palette = 15=${THEME_TEXT}

selection-background = ${THEME_SURFACE1}
selection-foreground = ${THEME_TEXT}
EOF

echo "Generated $OUTPUT"
