#!/bin/bash
# Renderer: Ghostty — maps THEME_NAME to built-in theme, falls back to custom generation.
set -euo pipefail

CONFIG="${DOTFILES_DIR}/modules/ghostty/config"
THEMES_DIR="${DOTFILES_DIR}/modules/ghostty/themes"

# Map THEME_NAME → Ghostty built-in theme name
get_builtin_theme() {
  case "$1" in
    catppuccin-mocha) echo "Catppuccin Mocha" ;;
    catppuccin-macchiato) echo "Catppuccin Macchiato" ;;
    dracula) echo "Dracula" ;;
    everforest) echo "Everforest Dark Hard" ;;
    gruvbox-dark) echo "Gruvbox Dark" ;;
    kanagawa) echo "Kanagawa Wave" ;;
    nord) echo "Nord" ;;
    rose-pine) echo "Rose Pine" ;;
    solarized-dark) echo "iTerm2 Solarized Dark" ;;
    tokyo-night) echo "TokyoNight Night" ;;
    *) echo "" ;;
  esac
}

name="${THEME_NAME:-gruvbox-dark}"
builtin=$(get_builtin_theme "$name")

if [[ -n "$builtin" ]]; then
  # Use Ghostty built-in theme — update config
  sed -i '' "s/^theme = .*/theme = ${builtin}/" "$CONFIG"
  # Remove custom theme file if it exists
  rm -f "$THEMES_DIR/my-theme"
  echo "  ✨ ghostty → ${builtin}"
else
  # No built-in match — generate custom theme file
  mkdir -p "$THEMES_DIR"
  sed -i '' "s/^theme = .*/theme = my-theme/" "$CONFIG"
  cat > "$THEMES_DIR/my-theme" <<EOF
# Generated by dotfiles theme system. Do not edit by hand.
background = ${THEME_BASE}
foreground = ${THEME_TEXT}
cursor-color = ${THEME_CURSOR}

palette = 0=${THEME_CRUST}
palette = 1=${THEME_RED}
palette = 2=${THEME_GREEN}
palette = 3=${THEME_YELLOW}
palette = 4=${THEME_BLUE}
palette = 5=${THEME_MAUVE}
palette = 6=${THEME_TEAL}
palette = 7=${THEME_OVERLAY1}
palette = 8=${THEME_OVERLAY0}
palette = 9=${THEME_MAROON}
palette = 10=${THEME_PEACH}
palette = 11=${THEME_SUBTEXT0}
palette = 12=${THEME_SAPPHIRE}
palette = 13=${THEME_SKY}
palette = 14=${THEME_FLAMINGO}
palette = 15=${THEME_TEXT}

selection-background = ${THEME_SURFACE1}
selection-foreground = ${THEME_TEXT}
EOF
  echo "  ✨ ghostty → my-theme (custom)"
fi
