#!/usr/bin/env bash
# Renderer: gitmux — YAML for ~/.gitmux.conf (installed by dotfiles-theme).
set -euo pipefail

OUTPUT="${DOTFILES_DIR}/system/themes/generated/gitmux.conf"

cat > "$OUTPUT" <<EOF
# Generated by theme system. Do not edit by hand.
tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: "↑·"
    behind: "↓·"
    staged: "● "
    conflict: "✖ "
    modified: "✚ "
    untracked: "… "
    stashed: "⚑ "
    clean: "✔"
    insertions: Σ
    deletions: Δ
  styles:
    clear: "#[fg=${THEME_TEXT}]"
    state: "#[fg=${THEME_RED},bold]"
    branch: "#[fg=${THEME_TEXT},bold]"
    remote: "#[fg=${THEME_TEAL}]"
    divergence: "#[fg=${THEME_SUBTEXT0}]"
    staged: "#[fg=${THEME_GREEN},bold]"
    conflict: "#[fg=${THEME_RED},bold]"
    modified: "#[fg=${THEME_YELLOW},bold]"
    untracked: "#[fg=${THEME_MAUVE},bold]"
    stashed: "#[fg=${THEME_BLUE},bold]"
    clean: "#[fg=${THEME_GREEN},bold]"
    insertions: "#[fg=${THEME_GREEN}]"
    deletions: "#[fg=${THEME_RED}]"
  layout: [branch, .., remote-branch, divergence, " - ", flags]
  options:
    branch_max_len: 24
    branch_trim: right
    ellipsis: …
    hide_clean: false
    swap_divergence: false
    divergence_space: false
EOF

echo "  ✨ gitmux.conf"
