#!/usr/bin/env bash
# Renderer: gitmux — YAML for ~/.gitmux.conf (installed by dotfiles-theme).
set -euo pipefail

OUTPUT="${DOTFILES_DIR}/system/themes/generated/gitmux.conf"

cat > "$OUTPUT" <<EOF
# Generated by theme system. Do not edit by hand.
tmux:
  symbols:
    branch: " "
    hashprefix: ":"
    ahead: "↑·"
    behind: "↓·"
    staged: "● "
    conflict: "✖ "
    modified: "✚ "
    untracked: "… "
    stashed: "⚑ "
    clean: "✔"
    insertions: Σ
    deletions: Δ
  styles:
    clear: "#[fg=${THEME_FG}]"
    state: "#[fg=${THEME_ERROR},bold]"
    branch: "#[fg=${THEME_FG},bold]"
    remote: "#[fg=${THEME_TERTIARY}]"
    divergence: "#[fg=${THEME_OUTLINE}]"
    staged: "#[fg=${THEME_SUCCESS},bold]"
    conflict: "#[fg=${THEME_ERROR},bold]"
    modified: "#[fg=${THEME_WARNING},bold]"
    untracked: "#[fg=${THEME_PRIMARY},bold]"
    stashed: "#[fg=${THEME_SECONDARY},bold]"
    clean: "#[fg=${THEME_SUCCESS},bold]"
    insertions: "#[fg=${THEME_SUCCESS}]"
    deletions: "#[fg=${THEME_ERROR}]"
  layout: [branch, .., remote-branch, divergence, " - ", flags]
  options:
    branch_max_len: 24
    branch_trim: right
    ellipsis: …
    hide_clean: false
    swap_divergence: false
    divergence_space: false
EOF

echo "  ✨ gitmux.conf"
