#!/bin/bash
# Renderer: Neovim — maps THEME_NAME to installed colorscheme plugin, falls back to gruvbox.
set -euo pipefail

OUTPUT="${DOTFILES_DIR}/system/themes/generated/nvim-theme.lua"

# Map THEME_NAME → Neovim colorscheme name + style
# Returns "colorscheme" or "colorscheme:style"
get_mapping() {
  case "$1" in
    catppuccin-mocha)     echo "catppuccin:mocha" ;;
    catppuccin-macchiato) echo "catppuccin:macchiato" ;;
    dracula)              echo "dracula" ;;
    everforest)           echo "everforest" ;;
    gruvbox-dark)         echo "gruvbox:dark" ;;
    kanagawa)             echo "kanagawa:wave" ;;
    nord)                 echo "nord" ;;
    rose-pine)            echo "rose-pine:main" ;;
    solarized-dark)       echo "solarized" ;;
    tokyo-night)          echo "tokyonight:night" ;;
    *)                    echo "" ;;
  esac
}

name="${THEME_NAME:-gruvbox-dark}"
mapping=$(get_mapping "$name")

if [[ -n "$mapping" ]]; then
  scheme="${mapping%%:*}"
  style="${mapping#*:}"
  [[ "$scheme" == "$style" ]] && style=""
else
  # No matching plugin — fallback to gruvbox
  scheme="gruvbox"
  style="dark"
  echo "  ⚠ nvim: no plugin match for '${name}', falling back to gruvbox"
fi

{
  echo "-- Generated by theme system. Do not edit by hand."
  echo "-- Set by: dotfiles theme apply ${name}"
  echo "vim.g.theme_colorscheme = \"${scheme}\""
  if [[ -n "$style" ]]; then
    echo "vim.g.theme_style = \"${style}\""
  fi
} > "$OUTPUT"

printf "  ✨ nvim-theme.lua\n"
