#!/bin/bash
# Renderer: Neovim — emits a Lua stub init.lua sources.
set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
OUTPUT="${DOTFILES_DIR}/system/themes/generated/nvim-theme.lua"

scheme="${THEME_NVIM_COLORSCHEME:-}"
style="${THEME_NVIM_STYLE:-}"

if [[ -z "$scheme" ]]; then
  echo "  ⚠ nvim: THEME_NVIM_COLORSCHEME not set for '${THEME_NAME:-?}', falling back to gruvbox"
  scheme="gruvbox"
  style="dark"
fi

{
  echo "-- Generated by theme system. Do not edit by hand."
  echo "-- Set by: dotfiles theme apply ${THEME_NAME:-unknown}"
  echo "vim.g.theme_colorscheme = \"${scheme}\""
  if [[ -n "$style" ]]; then
    echo "vim.g.theme_style = \"${style}\""
  fi
} > "$OUTPUT"

printf "  ✨ nvim-theme.lua\n"
