#!/usr/bin/env bash
# Renderer: Zsh/shell — exports THEME_* for new interactive shells (source from colors.sh).
set -euo pipefail

OUTPUT="${DOTFILES_DIR}/system/themes/generated/theme-env.sh"

_q() { printf '%q' "$1"; }

{
  echo "# Generated by theme system. Do not edit by hand."
  echo "# shellcheck disable=SC2034,SC2148"
  echo "export THEME_NAME=$(_q "${THEME_NAME:-}")"
  echo "export THEME_CRUST=$(_q "${THEME_CRUST}")"
  echo "export THEME_MANTLE=$(_q "${THEME_MANTLE}")"
  echo "export THEME_BASE=$(_q "${THEME_BASE}")"
  echo "export THEME_SURFACE0=$(_q "${THEME_SURFACE0}")"
  echo "export THEME_SURFACE1=$(_q "${THEME_SURFACE1}")"
  echo "export THEME_SURFACE2=$(_q "${THEME_SURFACE2}")"
  echo "export THEME_OVERLAY0=$(_q "${THEME_OVERLAY0}")"
  echo "export THEME_OVERLAY1=$(_q "${THEME_OVERLAY1}")"
  echo "export THEME_OVERLAY2=$(_q "${THEME_OVERLAY2}")"
  echo "export THEME_TEXT=$(_q "${THEME_TEXT}")"
  echo "export THEME_SUBTEXT1=$(_q "${THEME_SUBTEXT1}")"
  echo "export THEME_SUBTEXT0=$(_q "${THEME_SUBTEXT0}")"
  echo "export THEME_ROSEWATER=$(_q "${THEME_ROSEWATER}")"
  echo "export THEME_FLAMINGO=$(_q "${THEME_FLAMINGO}")"
  echo "export THEME_PINK=$(_q "${THEME_PINK}")"
  echo "export THEME_MAUVE=$(_q "${THEME_MAUVE}")"
  echo "export THEME_RED=$(_q "${THEME_RED}")"
  echo "export THEME_MAROON=$(_q "${THEME_MAROON}")"
  echo "export THEME_PEACH=$(_q "${THEME_PEACH}")"
  echo "export THEME_YELLOW=$(_q "${THEME_YELLOW}")"
  echo "export THEME_GREEN=$(_q "${THEME_GREEN}")"
  echo "export THEME_TEAL=$(_q "${THEME_TEAL}")"
  echo "export THEME_SKY=$(_q "${THEME_SKY}")"
  echo "export THEME_SAPPHIRE=$(_q "${THEME_SAPPHIRE}")"
  echo "export THEME_BLUE=$(_q "${THEME_BLUE}")"
  echo "export THEME_LAVENDER=$(_q "${THEME_LAVENDER}")"
  echo "export THEME_CURSOR=$(_q "${THEME_CURSOR}")"
  echo "export THEME_SUCCESS_HEX=$(_q "${THEME_GREEN}")"
  echo "export THEME_ERROR_HEX=$(_q "${THEME_RED}")"
  echo "export THEME_FOREGROUND_HEX=$(_q "${THEME_TEXT}")"
  echo "export THEME_BACKGROUND_HEX=$(_q "${THEME_BASE}")"
} > "$OUTPUT"

echo "  ✨ theme-env.sh"
