#!/usr/bin/env bash
# Renderer: shell — exports THEME_* for new interactive shells.
set -euo pipefail

OUTPUT="${DOTFILES_DIR}/system/themes/generated/theme-env.sh"

_q() { printf '%q' "$1"; }

{
  echo "# Generated by theme system. Do not edit by hand."
  echo "# shellcheck disable=SC2034,SC2148"
  echo "export THEME_NAME=$(_q "${THEME_NAME:-}")"
  echo "export THEME_DISPLAY_NAME=$(_q "${THEME_DISPLAY_NAME:-${THEME_NAME:-}}")"

  # Semantic
  for v in BG BG_ALT SHADOW FG PRIMARY SECONDARY TERTIARY ACCENT HOVER \
           SURFACE OUTLINE SUCCESS WARNING ERROR ORANGE; do
    name="THEME_${v}"
    echo "export ${name}=$(_q "${!name}")"
  done

  # ANSI 16
  for v in BLACK BLACKB RED REDB GREEN GREENB YELLOW YELLOWB \
           BLUE BLUEB MAGENTA MAGENTAB CYAN CYANB WHITE WHITEB; do
    name="THEME_${v}"
    echo "export ${name}=$(_q "${!name}")"
  done

  # Convenience aliases consumed by lib/modules/tools.sh and similar.
} > "$OUTPUT"

echo "  ✨ theme-env.sh"
