#!/usr/bin/env bash
# Renderer: SketchyBar — emits ARGB color vars consumed by sketchybar plugins.
# Naming convention used by widgets:
#   BLACK/WHITE/RED/...   Opaque palette (mapped from semantic THEME_*)
#   BAR_COLOR             Translucent bar background
#   BACKGROUND_2          Translucent surface (slider trough, etc.)
#   POPUP_*               Popup container styling
set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
# shellcheck source=../../lib/color.sh
source "$DOTFILES_DIR/system/lib/color.sh"

OUTPUT="${DOTFILES_DIR}/system/themes/generated/sketchybar-colors.sh"

BLACK=$(color_hex_to_argb "$THEME_BG")
WHITE=$(color_hex_to_argb "$THEME_FG")
RED=$(color_hex_to_argb "$THEME_ERROR")
GREEN=$(color_hex_to_argb "$THEME_SUCCESS")
BLUE=$(color_hex_to_argb "$THEME_SECONDARY")
YELLOW=$(color_hex_to_argb "$THEME_WARNING")
ORANGE=$(color_hex_to_argb "$THEME_ORANGE")
MAGENTA=$(color_hex_to_argb "$THEME_PRIMARY")
GREY=$(color_hex_to_argb "$THEME_OUTLINE")

# Translucent layers
BAR_BG=$(color_hex_to_argb "$THEME_BG" d9)         # 85% bar background
BAR_BORDER=$(color_hex_to_argb "$THEME_SURFACE" 60) # subtle border
SURFACE=$(color_hex_to_argb "$THEME_SURFACE" 60)    # slider/trough surface

cat > "$OUTPUT" <<EOF
#!/usr/bin/env bash
# Generated by theme system. Do not edit by hand.
export BLACK=${BLACK}
export WHITE=${WHITE}
export RED=${RED}
export GREEN=${GREEN}
export BLUE=${BLUE}
export YELLOW=${YELLOW}
export ORANGE=${ORANGE}
export MAGENTA=${MAGENTA}
export GREY=${GREY}
export TRANSPARENT=0x00000000
export BAR_COLOR=${BAR_BG}
export BAR_BORDER_COLOR=${BAR_BORDER}
export BACKGROUND_2=${SURFACE}
export ICON_COLOR=\$WHITE
export LABEL_COLOR=\$WHITE
export POPUP_BACKGROUND_COLOR=\$BAR_COLOR
export POPUP_BORDER_COLOR=\$GREY
EOF

echo "  ✨ sketchybar-colors.sh"
