#!/bin/bash
# Renderer: SketchyBar color variables
# Reads THEME_XX env vars and generates a shell script exporting ARGB colors.

set -euo pipefail

OUTPUT="${DOTFILES_DIR}/system/themes/generated/sketchybar-colors.sh"

# Strip leading '#' from hex colors
_base="${THEME_BASE#\#}"
_text="${THEME_TEXT#\#}"
_red="${THEME_RED#\#}"
_blue="${THEME_BLUE#\#}"
_teal="${THEME_TEAL#\#}"
_yellow="${THEME_YELLOW#\#}"
_mauve="${THEME_MAUVE#\#}"
_maroon="${THEME_MAROON#\#}"
_subtext0="${THEME_SUBTEXT0#\#}"
_surface2="${THEME_SURFACE2#\#}"
_surface0="${THEME_SURFACE0#\#}"

cat > "$OUTPUT" <<EOF
#!/bin/bash
# Generated by theme system. Do not edit by hand.
export BLACK=0xff${_base}
export WHITE=0xff${_text}
export RED=0xff${_red}
export GREEN=0xff${_blue}
export BLUE=0xff${_teal}
export YELLOW=0xff${_yellow}
export ORANGE=0xff${_mauve}
export MAGENTA=0xff${_maroon}
export GREY=0xff${_subtext0}
export TRANSPARENT=0x00000000
export BG0=0xff${_base}
export BG0O50=0x80${_base}
export BG0O60=0x99${_base}
export BG0O70=0xb2${_base}
export BG0O80=0xcc${_base}
export BG0O85=0x55${_base}
export BG1=0x60${_surface2}
export BG2=0x60${_surface0}
export BAR_COLOR=\$BG0O85
export BAR_BORDER_COLOR=\$BG2
export BACKGROUND_1=\$BG1
export BACKGROUND_2=\$BG2
export ICON_COLOR=\$WHITE
export LABEL_COLOR=\$WHITE
export POPUP_BACKGROUND_COLOR=\$BAR_COLOR
export POPUP_BORDER_COLOR=\$WHITE
export SHADOW_COLOR=\$BLACK
export MIC_LEVEL=40
EOF

echo "  ✨ sketchybar-colors.sh"
