#!/bin/bash
# Renderer: SketchyBar — exports ARGB color vars consumed by sketchybar plugins.
set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
# shellcheck source=../../lib/color.sh
source "$DOTFILES_DIR/system/lib/color.sh"

OUTPUT="${DOTFILES_DIR}/system/themes/generated/sketchybar-colors.sh"

# Opaque named colors (legacy ANSI-ish palette consumed by widgets).
BLACK=$(color_hex_to_argb "$THEME_BG")
WHITE=$(color_hex_to_argb "$THEME_FG")
RED=$(color_hex_to_argb "$THEME_ERROR")
GREEN=$(color_hex_to_argb "$THEME_SUCCESS")
BLUE=$(color_hex_to_argb "$THEME_SECONDARY")
YELLOW=$(color_hex_to_argb "$THEME_WARNING")
ORANGE=$(color_hex_to_argb "$THEME_ORANGE")
MAGENTA=$(color_hex_to_argb "$THEME_PRIMARY")
GREY=$(color_hex_to_argb "$THEME_OUTLINE")

# Translucent bar background — several alpha levels.
BG0=$(color_hex_to_argb "$THEME_BG")
BG0O50=$(color_hex_to_argb "$THEME_BG" 80)
BG0O60=$(color_hex_to_argb "$THEME_BG" 99)
BG0O70=$(color_hex_to_argb "$THEME_BG" b2)
BG0O80=$(color_hex_to_argb "$THEME_BG" cc)
BG0O85=$(color_hex_to_argb "$THEME_BG" 55)

# Translucent surface accents.
BG1=$(color_hex_to_argb "$THEME_OUTLINE" 60)
BG2=$(color_hex_to_argb "$THEME_SURFACE" 60)

cat > "$OUTPUT" <<EOF
#!/bin/bash
# Generated by theme system. Do not edit by hand.
export BLACK=${BLACK}
export WHITE=${WHITE}
export RED=${RED}
export GREEN=${GREEN}
export BLUE=${BLUE}
export YELLOW=${YELLOW}
export ORANGE=${ORANGE}
export MAGENTA=${MAGENTA}
export GREY=${GREY}
export TRANSPARENT=0x00000000
export BG0=${BG0}
export BG0O50=${BG0O50}
export BG0O60=${BG0O60}
export BG0O70=${BG0O70}
export BG0O80=${BG0O80}
export BG0O85=${BG0O85}
export BG1=${BG1}
export BG2=${BG2}
export BAR_COLOR=\$BG0O85
export BAR_BORDER_COLOR=\$BG2
export BACKGROUND_1=\$BG1
export BACKGROUND_2=\$BG2
export ICON_COLOR=\$WHITE
export LABEL_COLOR=\$WHITE
export POPUP_BACKGROUND_COLOR=\$BAR_COLOR
export POPUP_BORDER_COLOR=\$WHITE
export SHADOW_COLOR=\$BLACK
export MIC_LEVEL=40
EOF

echo "  ✨ sketchybar-colors.sh"
