#!/usr/bin/env bash
# Renderer: Starship prompt — minimal two-line config with theme colors.
set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"
# shellcheck source=../../lib/color.sh
source "$DOTFILES_DIR/system/lib/color.sh"
OUTPUT="${DOTFILES_DIR}/system/themes/generated/starship.toml"

PRIMARY=$(color_no_hash "$THEME_PRIMARY")
SECONDARY=$(color_no_hash "$THEME_SECONDARY")
SUCCESS=$(color_no_hash "$THEME_SUCCESS")
WARNING=$(color_no_hash "$THEME_WARNING")
ERROR=$(color_no_hash "$THEME_ERROR")
OUTLINE=$(color_no_hash "$THEME_OUTLINE")

cat >"$OUTPUT" <<EOF
# Generated by theme system. Do not edit by hand.
add_newline = true
command_timeout = 1500
scan_timeout = 50

format = """\$directory\$git_branch\$git_status\$cmd_duration
\$character"""

[character]
success_symbol = "[❯](bold #${PRIMARY})"
error_symbol   = "[❯](bold #${ERROR})"
vimcmd_symbol  = "[❮](bold #${SUCCESS})"

[directory]
style = "bold #${SECONDARY}"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"
read_only = " 󰌾"
read_only_style = "#${ERROR}"

[git_branch]
symbol = " "
style = "bold #${PRIMARY}"
format = "[\$symbol\$branch](\$style) "

[git_status]
style = "#${WARNING}"
format = '([\[\$all_status\$ahead_behind\]](\$style) )'
conflicted = "="
ahead = "⇡\${count}"
behind = "⇣\${count}"
diverged = "⇕⇡\${ahead_count}⇣\${behind_count}"
untracked = "?"
modified = "!"
staged = "+"
deleted = "✘"

[cmd_duration]
min_time = 2000
style = "italic #${OUTLINE}"
format = " [\$duration](\$style)"

[time]
disabled = true

[nodejs]
disabled = true
[python]
disabled = true
[rust]
disabled = true
[golang]
disabled = true
[java]
disabled = true
[docker_context]
disabled = true
EOF

echo "  ✨ starship.toml"
