#!/bin/bash
# Renderer: Starship prompt config
# Reads THEME_XX env vars and generates starship.toml with a custom palette.

set -euo pipefail

OUTPUT="${DOTFILES_DIR}/system/themes/generated/starship.toml"

# Static portion of the config
cat > "$OUTPUT" <<'STATIC'
# Generated by theme system. Do not edit by hand.
add_newline = false
format = """$directory$character"""
right_format = ""
command_timeout = 1000

[character]
success_symbol = "[[󰄛](green) ❯](peach)"
error_symbol = "[[󰄛](red) ❯](peach)"
vimcmd_symbol = "[󰄛 ❮](subtext0)"

[git_branch]
disabled = true

[git_status]
disabled = true

[directory]
truncation_length = 4
style = "bold lavender"

[palettes.custom]
STATIC

# Dynamic palette portion (variables get expanded)
cat >> "$OUTPUT" <<PALETTE
rosewater = "${THEME_ROSEWATER}"
flamingo = "${THEME_FLAMINGO}"
pink = "${THEME_PINK}"
mauve = "${THEME_MAUVE}"
red = "${THEME_RED}"
maroon = "${THEME_MAROON}"
peach = "${THEME_PEACH}"
yellow = "${THEME_YELLOW}"
green = "${THEME_GREEN}"
teal = "${THEME_TEAL}"
sky = "${THEME_SKY}"
sapphire = "${THEME_SAPPHIRE}"
blue = "${THEME_BLUE}"
lavender = "${THEME_LAVENDER}"
text = "${THEME_TEXT}"
subtext1 = "${THEME_SUBTEXT1}"
subtext0 = "${THEME_SUBTEXT0}"
overlay2 = "${THEME_OVERLAY2}"
overlay1 = "${THEME_OVERLAY1}"
overlay0 = "${THEME_OVERLAY0}"
surface2 = "${THEME_SURFACE2}"
surface1 = "${THEME_SURFACE1}"
surface0 = "${THEME_SURFACE0}"
base = "${THEME_BASE}"
mantle = "${THEME_MANTLE}"
crust = "${THEME_CRUST}"
PALETTE

printf "  ✨ starship.toml\n"
