#!/bin/bash
# Renderer: tmux color overrides
# Reads THEME_XX env vars and generates tmux @thm_ variable overrides.

set -euo pipefail

OUTPUT="${DOTFILES_DIR}/system/themes/generated/tmux-colors.conf"

cat > "$OUTPUT" <<EOF
# Generated by theme system. Do not edit by hand.
set -g @thm_bg "${THEME_BASE}"
set -g @thm_fg "${THEME_TEXT}"
set -g @thm_bg_dark "${THEME_CRUST}"
set -g @thm_dark "${THEME_MANTLE}"
set -g @thm_mid "${THEME_SURFACE0}"
set -g @thm_light "${THEME_SURFACE1}"
set -g @thm_accent "${THEME_MAUVE}"
set -g @thm_rosewater "${THEME_ROSEWATER}"
set -g @thm_flamingo "${THEME_FLAMINGO}"
set -g @thm_pink "${THEME_PINK}"
set -g @thm_mauve "${THEME_MAUVE}"
set -g @thm_red "${THEME_RED}"
set -g @thm_maroon "${THEME_MAROON}"
set -g @thm_peach "${THEME_PEACH}"
set -g @thm_yellow "${THEME_YELLOW}"
set -g @thm_green "${THEME_GREEN}"
set -g @thm_teal "${THEME_TEAL}"
set -g @thm_sky "${THEME_SKY}"
set -g @thm_sapphire "${THEME_SAPPHIRE}"
set -g @thm_blue "${THEME_BLUE}"
set -g @thm_lavender "${THEME_LAVENDER}"
set -g @thm_text "${THEME_TEXT}"
set -g @thm_subtext1 "${THEME_SUBTEXT1}"
set -g @thm_subtext0 "${THEME_SUBTEXT0}"
set -g @thm_overlay2 "${THEME_OVERLAY2}"
set -g @thm_overlay1 "${THEME_OVERLAY1}"
set -g @thm_overlay0 "${THEME_OVERLAY0}"
set -g @thm_surface2 "${THEME_SURFACE2}"
set -g @thm_surface1 "${THEME_SURFACE1}"
set -g @thm_surface0 "${THEME_SURFACE0}"
set -g @thm_base "${THEME_BASE}"
set -g @thm_mantle "${THEME_MANTLE}"
set -g @thm_crust "${THEME_CRUST}"
EOF

echo "Generated $OUTPUT"
