#!/bin/bash
# Renderer: tmux color overrides for the catppuccin/tmux plugin.
# We feed semantic colors into the plugin's @thm_* namespace so the existing
# status-bar config keeps working without depending on Catppuccin specifically.
set -euo pipefail

OUTPUT="${DOTFILES_DIR}/system/themes/generated/tmux-colors.conf"

cat >"$OUTPUT" <<EOF
# Generated by theme system. Do not edit by hand.
set -g @thm_bg "${THEME_BG}"
set -g @thm_fg "${THEME_FG}"
set -g @thm_bg_dark "${THEME_SHADOW}"
set -g @thm_dark "${THEME_BG_ALT}"
set -g @thm_mid "${THEME_SURFACE}"
set -g @thm_light "${THEME_OUTLINE}"
set -g @thm_accent "${THEME_PRIMARY}"

# Catppuccin plugin slots — mapped to closest semantic color.
set -g @thm_rosewater "${THEME_ACCENT}"
set -g @thm_flamingo  "${THEME_HOVER}"
set -g @thm_pink      "${THEME_HOVER}"
set -g @thm_mauve     "${THEME_PRIMARY}"
set -g @thm_red       "${THEME_ERROR}"
set -g @thm_maroon    "${THEME_ERROR}"
set -g @thm_peach     "${THEME_ORANGE}"
set -g @thm_yellow    "${THEME_WARNING}"
set -g @thm_green     "${THEME_SUCCESS}"
set -g @thm_teal      "${THEME_TERTIARY}"
set -g @thm_sky       "${THEME_TERTIARY}"
set -g @thm_sapphire  "${THEME_SECONDARY}"
set -g @thm_blue      "${THEME_SECONDARY}"
set -g @thm_lavender  "${THEME_ACCENT}"

set -g @thm_text      "${THEME_FG}"
set -g @thm_subtext1  "${THEME_FG}"
set -g @thm_subtext0  "${THEME_OUTLINE}"
set -g @thm_subtext_1 "${THEME_FG}"
set -g @thm_subtext_0 "${THEME_OUTLINE}"
set -g @thm_overlay2  "${THEME_OUTLINE}"
set -g @thm_overlay1  "${THEME_SURFACE}"
set -g @thm_overlay0  "${THEME_BG_ALT}"
set -g @thm_overlay_2 "${THEME_OUTLINE}"
set -g @thm_overlay_1 "${THEME_SURFACE}"
set -g @thm_overlay_0 "${THEME_BG_ALT}"
set -g @thm_surface2  "${THEME_SURFACE}"
set -g @thm_surface1  "${THEME_SURFACE}"
set -g @thm_surface0  "${THEME_SURFACE}"
set -g @thm_surface_2 "${THEME_SURFACE}"
set -g @thm_surface_1 "${THEME_SURFACE}"
set -g @thm_surface_0 "${THEME_SURFACE}"
set -g @thm_base   "${THEME_BG}"
set -g @thm_mantle "${THEME_BG_ALT}"
set -g @thm_crust  "${THEME_SHADOW}"

set -g @floax-border-color "${THEME_PRIMARY}"
set -g @floax-text-color "${THEME_FG}"
EOF

echo "  ✨ tmux-colors.conf"
